language: php
php:
  - '7.1'
  - '7.2'

script:
#  - composer self-update
  - composer install
  - ./vendor/bin/phpunit --coverage-clover ./tests/coverageData/clover

after_script:
  - php vendor/bin/codacycoverage clover ./tests/coverageData/clover

notifications:
  email: false