language: php
php:
  - '7.1'
  - '7.2'

script:
#  - composer self-update
  - composer install --dev
  - export CODACY_PROJECT_TOKEN=$CODACY_TOKEN
  - ./vendor/bin/phpunit  --coverage-clover build/coverage/xml

after_script:
  - php vendor/bin/codacycoverage clover build/coverage/xml

notifications:
  email: false