language: php
php:
  - '7.1'
  - '7.2'

script:
#  - composer self-update
  - composer install
  - ./vendor/bin/phpunit --coverage-xml ./tests/coverageData

after_script:
  - php vendor/bin/codacycoverage phpunit ./tests/coverageData

notifications:
  email: false