language: php
php:
  - '7.1'
  - '7.2'

addons:
  mariadb: '10.0'

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS ugamela_testing;'
  - mysql -u root --default-character-set=utf8 ugamela_testing < ./tests/database.sql

script:
#  - composer self-update
  - composer install
  - ./vendor/bin/phpunit --coverage-clover ./build/coverage/xml

after_script:
  - php vendor/bin/codacycoverage clover ./build/coverage/xml

notifications:
  email: false